# Generated by Django 4.1.3 on 2022-11-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='trabajos_anteriores',
            field=models.CharField(max_length=1000),
        ),
    ]
